[build]
  command = "npm run build"
  publish = "dist"

# Single Page App fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers utiles
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
